### ISSUE TITLE
check_snmp_raid and multiple controllers

### ISSUE THREAD

**Issue by erezzarum** [willixix/naglio-plugins#28] opened 2013-05-06 14:26 UTC
It doesn't handle multiple controllers well, the support is not there at all, especially when using an enclosure.
I have managed to test the sasraid only (i own a bunch of megaraid cards).

**Comment by willixix** [comment] 2013-05-06 16:44
It used to work but its been a very long time since I tested it with multiple controllers (probably in 2007 old scsi megaraid + one sas along with it). What particular doesn't work?

**Comment by willixix** [comment] 2013-05-06 16:45
And if you're able to fix it yourself and provide a patch or a pull request, it'd be much appreciated!

**Comment by erezzarum** [comment] 2013-05-07 07:45
The physical device table shows the devices from all the controllers, the oid doesn't break down correctly (a lot of vendors don't know how to expose snmp correctly) so you get all the physical devices from all the controllers, you have to map them by a controller (using the physical device to adapter OID).
The goodcount,badcount, etc... is an OID that will count only the first controller (controller 0) so if you have a bad device in the second controller it will not detect it.
I will fork the repo and try to fix it (it will be fixed only for the sasraid type as i don't have access to any other controllers), haven't touched Perl in about 2 years (though i like the net-snmp implementation in Perl more than i do in Python ;) )
And btw, thank you for sharing your plugin!

**Comment by erezzarum** [comment] 2013-05-07 10:12
I have forked and made some changes.
I have also increased the maxmsgsize.
My Perl skills are quite rusty, i will be happy if you can review it, i will try to add more features to it as well.

**Comment by willixix** [comment] 2013-05-07 17:26
Ok, this I'd need to work on more in dev branch. Send me it as a patch by email and I'll apply it there.

The issue is too many table lookups and this plugin is one of the longest running if you time it. I'm trying to minimize queries for simple default cases so lookups in extra tables for multiple controllers would have to go as an option for those who need it. Also msgsize will become an option as well rather than setting to 16k as default. And I'll also import my new SNMP functions from another plugin for bulk snmp.

**Comment by erezzarum** [comment] 2013-05-08 08:54
I tried to optimize it, but it's quite hard, especially when you have large amount of disks.
The run time for around 100 disks takes about 15s, i run those checks at 5mins interval, the slowness is not from the script itself but comes from the LSI SNMP module which is slow.
As example, i monitor a few switches, each "switch" is a stack that has 96 ports total, the run time to get all the interface stats (out,in,errors, etc..) is around 2s, that's because the SNMP output itself is fast, if i compare it to the LSI request, the request itself is very slow (LSI needs to optimize it)

**Comment by willixix** [comment] 2013-06-25 20:08
I have released new version of check_smp_raid.pl with your patch for multiple controllers. It is in both master and dev branches now. Will be closing this issue now. Thank you for your contributions.

**Closed as completed by willixix** 2013-06-25 20:08 UTC
